apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.operator_namespace }} 
  labels:
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/managed-by: {{ .Values.managed_by }}
    app.kubernetes.io/name: {{ .Values.name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncwave | default "-5" | quote }}   
spec:
  {{- toYaml .Values.spec | nindent 2 }}